# Generated by Django 2.2.12 on 2021-05-02 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic_Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('issue', models.CharField(default='', max_length=500)),
                ('severity', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('cpu', models.CharField(default='', max_length=100)),
                ('memory', models.CharField(default='', max_length=100)),
                ('storage', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('dustlevel', models.FloatField()),
                ('enviro_temprature', models.FloatField()),
                ('sys_temprature', models.FloatField()),
                ('brightness', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('barometer_temperature', models.FloatField()),
                ('barometer_pressure', models.IntegerField()),
                ('human_detection', models.CharField(default='', max_length=100)),
                ('batterylevel', models.IntegerField(null=True)),
                ('longitude', models.CharField(default='0.000', max_length=200)),
                ('latitude', models.CharField(default='0.000', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=500)),
                ('dateandtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('activity', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
