# Generated by Django 2.2.12 on 2021-02-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainFrame', '0006_accountactivity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='dustlevel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
