# Generated by Django 2.2.12 on 2021-02-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainFrame', '0007_sensordata_dustlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='dustlevel',
            field=models.FloatField(),
        ),
    ]
