# Generated by Django 2.2.12 on 2021-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainFrame', '0008_auto_20210205_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='barometer_pressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='barometer_temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='brightness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='enviro_temprature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sys_temprature',
            field=models.FloatField(),
        ),
    ]
