# Generated by Django 2.2.12 on 2021-01-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=500)),
                ('dateandtime', models.DateField()),
            ],
        ),
    ]
