# Generated by Django 2.2.12 on 2021-01-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainFrame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('cpu', models.CharField(default='', max_length=100)),
                ('memory', models.CharField(default='', max_length=100)),
                ('storage', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
