# Generated by Django 2.2.12 on 2021-01-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainFrame', '0002_resourcelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('enviro_temprature', models.CharField(default='', max_length=100)),
                ('sys_temprature', models.CharField(default='', max_length=100)),
                ('brightness', models.CharField(default='', max_length=100)),
                ('humidity', models.CharField(default='', max_length=100)),
                ('barometer_temperature', models.CharField(default='', max_length=100)),
                ('barometer_pressure', models.CharField(default='', max_length=100)),
                ('human_detection', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
