# Generated by Django 2.2.12 on 2021-01-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainFrame', '0003_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic_Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('issue', models.CharField(default='', max_length=500)),
                ('severity', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
